name: mmc_master
description: A new Flutter project.

publish_to: 'none'

version: 3.0.11+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share: ^2.0.4
  flutter_speed_dial: ^5.0.0+1
  font_awesome_flutter: ^9.2.0
  maps_places_autocomplete:
  google_maps_flutter: ^2.1.3
  webview_flutter: ^3.0.3
  modal_progress_hud: ^0.1.3
  search_map_location: ^0.0.5
  cached_network_image: ^2.0.0
  image_picker: ^0.8.4+4
  provider: ^6.0.1
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  get:
  intl: ^0.17.0
  simple_animations: ^1.3.3
  google_fonts: ^3.0.1
  nb_utils: ^4.5.2
  intl_phone_field: ^2.1.0
  pin_entry_text_field: ^0.1.4
  table_calendar: ^3.0.4
  dio:
  path_provider:
  image_gallery_saver:
  permission_handler:
  flutter_spinkit: ^5.1.0
  weather:
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  bubble: ^1.1.9+1
  spincircle_bottom_bar: ^2.0.0
  flutter_local_notifications: ^9.2.0
  firebase_analytics: ^9.1.9
  flutter_map:
  latlong2: ^0.8.1
  proj4dart: ^2.0.0
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  positioned_tap_detector_2: ^1.0.4
  flutter_share: ^2.0.0
  flutter_mobx: ^2.0.6+1
  carousel_slider: ^3.0.0
  transparent_image: ^2.0.0
  flutter_html:
  url_launcher:
  new_version: ^0.3.1
  quickalert:
  in_app_review:
  google_sign_in:
  csv:
  text_to_speech:
  circle_nav_bar: ^2.0.1+1
  pinput:
  translator:
  firebase_storage:
  cloud_firestore: ^2.5.3
  shimmer:
  flutter_svg:

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  hive_generator:

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icon/
    - assets/new_images/
    - assets/Banners/
    - assets/new_icons/
    - assets/
    - assets/images/default.jpg
    - assets/images/robot.jpg
    - assets/images/robot.png
    - assets/images/camera.png
    - assets/images/fertiliser.png
    - assets/images/expert.png
    - assets/images/factory.png
    - assets/images/weather.png
    - assets/images/ferti.png
    - assets/images/chatbot.png
    - assets/images/dise.png
    - assets/images/ThirdScreen1.png
    - assets/images/ThirdScreen2.png
    - assets/images/ThirdScreen3.png
    - assets/new_images/facebook logo.png
    - assets/new_images/Google logo.png
    - assets/images/weatherico.png
    - assets/images/cropguide.png
    - assets/images/more.png
    - assets/images/Disease detection.png
    - assets/images/Add_Farm.png
    - assets/images/scouting.png
    - assets/images/Detection.png
    - assets/images/Planner.png
    - assets/images/Schedule.png
    - assets/images/Image_download.png
    - assets/images/Markets.png
    - assets/new_images/Global.png
    - assets/new_images/India.png
    - assets/new_images/Farms.png
    - assets/new_images/cropguide.png
    - assets/new_images/Detection.png
    - assets/new_images/Community_Horizontal.png
    - assets/new_images/Planner.png
    - assets/new_images/Schedule a call.png
    - assets/new_images/Markets.png
    - assets/new_images/India_crop_guide.png
    - assets/new_images/Global crop guide.png
    - assets/Banners/Banner 1.png
    - assets/Banners/Banner 2.png
    - assets/Banners/Banner 3.png
    - assets/Banners/Farms Added.png
    - assets/Banners/market.png
    - assets/Banners/Disease Detection.png
    - assets/Csv/
    - assets/illustrations/
    - assets/amsr2.png
    - assets/Banking_ic_Logout.png
    - assets/svgImages/


  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-Light.ttf


flutter_intl:
    enabled: true